// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70s0iv_CGmU44x-KyXNGW2iG6BdBRXJ0',
    appId: '1:443479354803:web:51d725ba9f68a5f99f2fc6',
    messagingSenderId: '443479354803',
    projectId: 'ecommercetest-b2ae9',
    authDomain: 'ecommercetest-b2ae9.firebaseapp.com',
    databaseURL: 'https://ecommercetest-b2ae9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercetest-b2ae9.appspot.com',
    measurementId: 'G-FX2Y6C7JJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_rjYOwGryJdzD0lT6PZcT7X1-fGo-Ro',
    appId: '1:443479354803:android:dd0cd9fd868b820d9f2fc6',
    messagingSenderId: '443479354803',
    projectId: 'ecommercetest-b2ae9',
    databaseURL: 'https://ecommercetest-b2ae9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercetest-b2ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhfNGeydQ_W4U65Wk9oeg4y2heHrxVgg',
    appId: '1:443479354803:ios:761d0584882ffc8a9f2fc6',
    messagingSenderId: '443479354803',
    projectId: 'ecommercetest-b2ae9',
    databaseURL: 'https://ecommercetest-b2ae9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercetest-b2ae9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhfNGeydQ_W4U65Wk9oeg4y2heHrxVgg',
    appId: '1:443479354803:ios:761d0584882ffc8a9f2fc6',
    messagingSenderId: '443479354803',
    projectId: 'ecommercetest-b2ae9',
    databaseURL: 'https://ecommercetest-b2ae9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercetest-b2ae9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA70s0iv_CGmU44x-KyXNGW2iG6BdBRXJ0',
    appId: '1:443479354803:web:47ab074799b6fa1f9f2fc6',
    messagingSenderId: '443479354803',
    projectId: 'ecommercetest-b2ae9',
    authDomain: 'ecommercetest-b2ae9.firebaseapp.com',
    databaseURL: 'https://ecommercetest-b2ae9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercetest-b2ae9.appspot.com',
    measurementId: 'G-BVFKK2EJQY',
  );
}
